### PR TITLE
[hold][WIP] Comment form improvements

### PR DESCRIPTION
**Pull request by abought**
## Ticket

https://openscience.atlassian.net/browse/EOSF-100
# Purpose

Bring comment form to parity with OSF widgets.

This is intended to look and work like existing OSF widgets, to minimize the disruption of moving between pages during an incremental migration.
## Status

On hold, as we shifted priorities to implementing different pages. Keeping PR open to track work and blockers.
### Short-term deliverables:
- Styling
- Button and error functionality
- Validation
- Threading support
### Future improvements needed for parity
- Support viewing anonymous projects (don't represent author information in the comment display field)
- Render markdown in comment fields
- Support `@mention` functionality
- Comment reporting
## Long-term improvements
- Improve markup accessibility (eg icons need [titles](http://fontawesome.io/accessibility/))
## TODO

Core UI and features
- Threads
  - [x] Support UI
  - [x] Support threads for replies
- [ ] Loading state indicators 
- Generalize comment-form
  - [x] offer add and edit modes
  - [x] Support validation
- @mentions and markdown rendering

Additional features 
- Pagination behavior parity
  - [ ] fetch-more only when user has read through results on page, eg ember-infinity)
  - [ ] Do not limit comments page (or replies) to 10 comments only
- [ ] Display unread reply counts (in navbar "open comments pane" button). See [OSF-4656](https://openscience.atlassian.net/browse/OSF-4656) for docs on required API query param.
- [ ] Add error handling for many scenarios. Pages are built on assumption everything succeeds.

Adapter requirements
- Make requests using the following query params
  - [ ] embed=user
  - [ ] `filter[target]=<cid>` (built into rel url already, make sure it's respected)
  - [ ] `page[size]=30`
## Known issues
- [x] Creating a comment, then deleting it, leads to 409 errors. This is because the client-only dummy fields (targetID and targetType) are still there in the local store, and therefore are still getting serialized.
- [ ] The comment form should not clear if `submitComment` fails. (don't provisionally render the comment!)
- Replies
  - [ ] Sometimes replying sends a server request. This is tied to an adapter issue where multiple sequential operations do not always trigger an operation immediately. (eg the first attempt to reply may fail, but the second attempt to reply may cause both replies to be sent)
  - [ ] Gravatar doesn't show for newly created replies, sans reload.
# Notes for Reviewers

To be written
## Routes Added/Updated

See sample comment widgets on node detail page, eg
http://localhost:4200/nodes/m9pv6

### CODE REVIEW

**Comment by abought** [comment]
The old comments page had some dead code related to anonymous/ view-only links. This OSF PR might be relevant- a possible behavior change on the OSF may simplify what the new ember-osf comments widget has to do as well.

https://github.com/CenterForOpenScience/osf.io/pull/6356

**Comment by abought** [comment]
By now this is likely very out of date, and the associated ticket was closed in January by @brianjgeiger .

I'd like to help keep the open pull requests list clean, and at one point Henrique was working on an extension of this PR. Has this been scrapped? Or is there an alternate branch that takes precedence? Can I close this PR?

**Comment by brianjgeiger** [comment]
Yeah, I was spring cleaning a bunch of issues a while back, and this was closed with those. Since this PR isn't linked with a ticket, I think it can be closed. If something else is an extension of this, it's either been pulled into another branch already or is likely going to have to go through a lot of additional work otherwise, yes?

**Comment by abought** [comment]
I'll go ahead and close this, since it doesn't sound like commenting is an issue we are presently tracking. There are perpetual rumors of a discourse commenting feature that might render this ticket superfluous, but no idea on the status there.

> Since this PR isn't linked with a ticket, I think it can be closed. 
Strictly speaking it is linked to a ticket, just not an open one. *Some* commenting feature would be required if we still want to rewrite many core OSF pages in ember.

> If something else is an extension of this, it's either been pulled into another branch already or is likely going to have to go through a lot of additional work otherwise, yes?
Henrique had a branch that picked this up, ~6-7 months ago. I do not know where that branch is or the current status.

**Pull request closed without merging**
