### PR TITLE
[review] Tweaks to support NPM packaging [#EOSF-446]

### PR DESCRIPTION
**Pull request by abought**
## Ticket
https://openscience.atlassian.net/browse/EOSF-446

# Purpose
Update package.json and .npmignore to generate a reasonable NPM package. This will make ember-osf easier to install, and allow us to support clear versioning.

- Update metadata so people can find us better
- Exclude more files via .npmignore so that packages are smaller, and don't contain sensitive info
- Encourage package + documentation to get updated together, in a way that stays consistent.
- Make it easier to release a new version without missing any steps.

# Notes for Reviewers
### Cutting a new release

- [x] Run `npm run bump-version minor`
- [x] Verify that package.json has changed, eg that `version` is now `0.3.0`
- [x] Open `docs/index.html` and verify that the documentation shows the current new version, after the increment.
- [x] Verify that this command does not generate any new commits or change the branch.
- [x] Verify that the `bump-version` command fails if any branch other than `develop`
- [x] Verify that the `make-release` command fails if any branch other than `develop`

### Verifying the npm package is good
If running locally, see these instructions to test package is installable.
https://docs.npmjs.com/misc/developers#before-publishing-make-sure-your-package-installs-and-works

In particular, **make sure the generated package excludes sensitive data**, like config/local.yml!

## Build/ release automation
This script contains some experimental automation of the release process via `npm run make-release`. We'd want to look closely at the design tradeoffs to see if this is worth it.

#### What is done automatically (design intent)
The current `preversion` + `postversion` hooks enforce the following release steps:

- Verify that the user is on the `develop` branch (and therefore presumed ready to cut a release)
- Verify that all unit tests pass locally
- Increment release version number `npm run make-release <version-number | semver flag> `
- Build updated doc version

Separately, the `make-release` command is a wrapper for git flow that automatically fetches the desired version number from package.json. (version was selected in a previous command- we want docs and release tags to be consistent)
- Run `git flow` to cut a new release, and commit it to master. (**Does not push the commits or tags to remote)

 Auto-incrementing of release version is [based on](https://docs.npmjs.com/cli/version) semver specification).

#### What is not done automatically
- The user is responsible for running `git flow init` in that repo at least once before making a release.
- A new release is generated, but not pushed to github. The user must manually `git push` and `git push --tags` after inspecting the release and verifying that the package is complete as written.

## TODO
- [x] Look into automating doc update, version build, and possibly any required git flow steps for a streamlined release + publish process
- [x] Consider guidelines that call for publishing only from a clean directory. Learn from our peers! http://emberjs.com/blog/2016/12/14/security-incident-aws-s3-key-exposure.html

## Routes Added/Updated
none

### CODE REVIEW

**Comment by abought** [comment]
> My only suggestion would be to put documentation for these new scripts in the README file (or an equally appropriate place) so that we won't have to go searching through PRs or the commit history.

These are good suggestions. I've updated the README, and also made the `package.json` license field consistent with our repo. (so that the NPM registry will list us correctly)

**Comment by brianjgeiger** [comment]
@abought Merge conflicts

**Comment by abought** [comment]
> @abought Merge conflicts

What, again?

Thanks for the heads-up...

**Comment by abought** [comment]
Merge conflicts addressed.

Oh, and coveralls is reporting!

**Comment by abought** [comment]
Note during validation:

When testing local install, use `npm install file:../ember-osf`. There appears to be a known bug where yarn ignores the `.npmignore` file, resulting in some messy packages.
See: 

`https://github.com/yarnpkg/yarn/issues/685`
`https://github.com/yarnpkg/yarn/issues/2090`

And my personal favorite, 
`https://github.com/yarnpkg/yarn/pull/465`

**Pull request merged**
