### PR TITLE
Add hideSearch component param to osf-navbar

### PR DESCRIPTION
**Pull request by hmoco**

### CODE REVIEW

**Comment by abought** [comment]
Can you provide documentation for this parameter, and a default value in the controller in case the user doesn't specify one?  Future users of the component should be able to figure out what it does and how to use it/ where it comes from.

This is one area where ember components are kind of weird- it's not always easy to reuse them across different projects. Working from example gets harder when the examples are in many different github repos!

Sample usage example: https://github.com/abought/ember-osf/blob/ea1462dfd277155da6a3d803075fd7e375bb8638/addon/components/eosf-project-nav/component.js#L15-L19
YUIDoc sample format for an individual property, https://github.com/abought/ember-osf/blob/368ecb93941976f91d67a8317f017fdb84d01fcd/addon/components/tags-widget/component.js#L32-L32

The result of those docstrings is something like this (we use YUIDoc format):
https://abought.github.io/ember-osf/classes/tags-widget.html

**Comment by hmoco** [comment]
@abought let me know when you can merge this

**Comment by abought** [comment]
Also- I can fix this later, but it seems like some information got lost in a merge commit as we both updated the sample usage.

https://github.com/CenterForOpenScience/ember-osf/blob/develop/addon/components/osf-navbar/component.js#L10-L17

**Comment by abought** [comment]
Looks good. Will merge when tests passing.

**Pull request merged**
